version: "3.9"
services:
  tasklistnode:
    build: .
    ports:
      - "3005:3000"
      - "3006:3000"
    links:
      - monguito
    environment:
      - DATABASE_HOST=mongodb://admin:123456@monguito:27017/tasklistdb?authSource=admin
      #prod -> mongodb://lactaconsejosusr:y9ku6E0LnDEPWat8@lactaconsejoscluster.ceqb5xi.mongodb.net/?retryWrites=true&w=majority
  monguito:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongo-data:/data/db
      #mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data
volumes:
  mongo-data: