FROM node:18

# Create app directory
WORKDIR /home/app

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Creates a "dist" folder with the production build
#RUN npm run build

EXPOSE 3005

# CMD [ "nest start --watch" ]